conditioning:
  method:  rt-ps+ #ps+ #
  params:
    scales: [0.1,1.0]
    scale_method: step
    use_log: true
    
data:
  name: ffhq
  root: ./data/streetlearn  

measurement:
  operator:
    name: raytracing-
    scene_name: 
    image_path: 
    ldr: false
    n_images: 60
    
    scene_path: 
    camera_path: 
    illumi_gamma: 6.0
    illumi_scale: 10.0
    illumi_normalize: 0.9
    texture_res: 256
    
  noise: 
    name: gaussian
    sigma: 0.05
